
FROM golang:alpine as builder
RUN apk --no-cache add git dep ca-certificates
RUN mkdir -p /go/src/katalog
# ADD ./Gopkg.toml /go/src/katalog
ADD ./vendor /go/src/
COPY ./src /go/src/github.com/walmartdigital/katalog
COPY ./health.sh /go/src/github.com/walmartdigital/katalog
# WORKDIR /go/src/katalog
# RUN go mod vendor
WORKDIR /go/src/github.com/walmartdigital/katalog
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .

FROM alpine
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/walmartdigital/katalog /app/
# COPY --from=builder /bin/stat /bin/stat
WORKDIR /app
ENTRYPOINT ["./main"]